version: '3.7'

# Docker networks
networks:
    app-networks:
        driver: bridge

# Docker services
services:
    # PHP and Nginx
    laravel-app:
        container_name: laravel-app
        platform: linux/x86_64
        restart: unless-stopped
        build: ./docker/php
        ports:
            - "9000:80"
        volumes:
            - ./:/usr/share/nginx
        depends_on:
            - mysql-app
            - redis-app
        networks:
            - app-networks

    # MySQL
    mysql-app:
        container_name: mysql-app
        image: mysql:latest
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME} # não pode ser root
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3399:3306"
        networks:
            - app-networks

    # Redis
    redis-app:
        container_name: redis-app
        image: redis:latest
        restart: unless-stopped
        volumes:
            - ./.docker/redis/data:/data
        ports:
            - "6379:6379"
        networks:
            - app-networks

    horizon-app:
        container_name: horizon-app
        platform: linux/x86_64
        restart: unless-stopped
        build: ./docker/php
        volumes:
            - ./:/usr/share/nginx
        depends_on:
            - laravel-app
        command: php artisan horizon
        networks:
            - app-networks
