version: '3'

services:
    app-laravel:
        container_name: app-laravel
        platform: linux/x86_64
        build: .
        ports:
            - "9000:80"
        volumes:
            - ./:/usr/share/nginx
        networks:
            - app-networks

    app-mysql:
        container_name: app-mysql
        image: mysql:latest
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3389:3306"
        networks:
            - app-networks

networks:
    app-networks:
        driver: bridge
